[package]
name = "rust-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bzip2 = "0.4.3"

[profile.release]
# lto = "fat"
codegen-units = 1
# opt-level = 3
